am62x: rgx_um: add rogueddk_1.18@6276027 prebuilts libs and bins
add prebuilts libs and bins from DDK version 1.18

Signed-off-by: Guillaume La Roque <glaroque@baylibre.com>

diff --git a/rgx_um/vendor/bin/pvrhwperf b/rgx_um/vendor/bin/pvrhwperf
--- a/rgx_um/vendor/bin/pvrhwperf
+++ b/rgx_um/vendor/bin/pvrhwperf
@@ -1,8 +1,15 @@
+#!/bin/sh
+
 OS="LINUX"
 TMP_ROOT="/tmp"
 TXT_READER=more
 CAT_LOG=no
 RETAIN_TL_HEADERS=no
+
+DEVICE="all"
+DEVICES=0
+MIN_DEVICE_ID=0
+MAX_DEVICE_ID=15
 
 HWPERF_FW_FILTER=""
 HWPERF_HOST_FILTER=""
@@ -37,25 +44,36 @@ fi
 preserve_state() {
   PVR_DBG_LEVEL_OLD="$PVRDebugLevel"
 
-  if [ x"$HWPERF_FW_FILTER" != x ] && [ -f $HWPERF_FW_FILTER_FILE ]; then
-    HWPERF_FW_FILTER_OLD=$(cat $HWPERF_FW_FILTER_FILE)
-  fi
+  for ID in $DEVICES; do
+    eval "_FW_FILTER_FILE=\$HWPERF_FW_FILTER_FILE_$ID"
+    if [ x"$HWPERF_FW_FILTER" != x ] && [ -f $_FW_FILTER_FILE ]; then
+      eval "HWPERF_FW_FILTER_${ID}_OLD=\"\$(cat $_FW_FILTER_FILE)\""
+    fi
 
-  if [ x"$HWPERF_HOST_FILTER" != x ] && [ -f $HWPERF_HOST_FILTER_FILE ]; then
-    HWPERF_HOST_FILTER_OLD=$(cat $HWPERF_HOST_FILTER_FILE)
-  fi
+    eval "_HOST_FILTER_FILE=\$HWPERF_HOST_FILTER_FILE_$ID"
+    if [ x"$HWPERF_HOST_FILTER" != x ] && [ -f $_HOST_FILTER_FILE ]; then
+      eval "HWPERF_HOST_FILTER_${ID}_OLD=\"\$(cat $_HOST_FILTER_FILE)\""
+    fi
+  done
 }
 
 restore_state() {
   export PVRDebugLevel=$PVR_DBG_LEVEL_OLD
 
-  if [ x"$HWPERF_FW_FILTER_OLD" != x ]; then
-    echo $HWPERF_FW_FILTER_OLD > $HWPERF_FW_FILTER_FILE
-  fi
+  for ID in $DEVICES; do
+    eval "_FW_FILTER=\$HWPERF_FW_FILTER_${ID}_OLD"
+    eval "_FW_FILTER_FILE=\$HWPERF_FW_FILTER_FILE_${ID}"
+    if [ x"$_FW_FILTER" != x ]; then
+      echo $_FW_FILTER > $_FW_FILTER_FILE
+    fi
 
-  if [ x"$HWPERF_HOST_FILTER_OLD" != x ]; then
-    echo $HWPERF_HOST_FILTER_OLD > $HWPERF_HOST_FILTER_FILE
-  fi
+    eval "_HOST_FILTER=\$HWPERF_HOST_FILTER_${ID}_OLD"
+    eval "_HOST_FILTER_FILE=\$HWPERF_HOST_FILTER_FILE_${ID}"
+
+    if [ x"$_HOST_FILTER" != x ]; then
+      echo $_HOST_FILTER > $_HOST_FILTER_FILE
+    fi
+  done
 }
 
 OUT1_JSON_FILE_PREFIX="hwperf_fw_"
@@ -76,6 +94,10 @@ do
   fi
 
   case "$curr" in
+    -device)
+         DEVICE=$next
+         skip_next="true"
+        ;;
     -t)  EXEC_LINE=$H2J_NAME
          OUT1_JSON_FILE_TMP=$OUT1_JSON_FILE_PREFIX"*.json"
          OUT1_JSON_FILE="./"
@@ -100,13 +122,16 @@ do
          echo "| pvrhwperf : run pvrtld (Transport Layer Daemon) for gathering HWPerf data"
          echo "|"
          echo "|             The HWPerf output data (firmware, host and client) is generated"
-         echo "|             per-device and is segregated accordingly in files named"
-         echo "|             hwperf_[fw/host]_<DeviceNumber>.[bin/json] and"
-         echo "|             hwperf_client_<DeviceNumber>_<PID>.[bin/json] where <DeviceNumber>"
-         echo "|             is unique identifier for a rogue device (render node ID in-case"
-         echo "|             of Linux based platforms)"
+         echo "|             per-device and is segregated accordingly in files named:"
+         echo "|             * hwperf_fw_<DeviceID>.[bin/json]"
+         echo "|             * hwperf_host_<DeviceID>.[bin/json]"
+         echo "|             * hwperf_client_<DeviceID>_<PID>.[bin/json]"
+         echo "|             where <DeviceID> is unique identifier for a GPU device."
          echo "+-----------------------------------------------------------------------------+"
          echo "| Usage:"
+         echo "|     -device ID : Device ID (0-15 or \"all\") for which data will be captured"
+         echo "|                  (default \"all\"). If not specified or \"all\", data from all"
+         echo "|                  devices will be captured."
          echo "|     -t  : Call hwperfbin2jsont (if present), to process the generated"
          echo "|           *.bin output files, after pvrtld end."
          echo "|     -rt : Call hwperfbin2jsont, adding the -raw parameter, to process the"
@@ -159,6 +184,20 @@ else
   JSM_BIN="`which \"$JSM_NAME\"`"
 fi
 
+if [ x"$DEVICE" != xall ]; then
+  if ! [ $DEVICE -ge $MIN_DEVICE_ID ] 2>/dev/null; then
+    echo "[Error] invalid device id"
+    exit 1
+  fi
+  if ! [ $DEVICE -le $MAX_DEVICE_ID ] 2>/dev/null; then
+    echo "[Error] invalid device id"
+    exit 1
+  fi
+  if [ ${DEVICE} -lt 10 ]; then
+    DEVICE="0"${DEVICE}
+  fi
+fi
+
 if [ ! -f "$TLD_BIN" ]; then
   echo "[Error] pvrtld not found"
   exit 1
@@ -192,22 +231,8 @@ OUT1_FILE="./"
 OUT2_FILE="./"
 OUT3_DIR="./"
 
-if [ -d "/sys/kernel/debug/pvr" ]; then
-  DEBUG_DIR="/sys/kernel/debug/pvr"
-elif [ -d "/proc/pvr" ]; then
-  DEBUG_DIR="/proc/pvr"
-else
-  echo "Error: No valid debug path (Neither /sys/kernel/debug/pvr or /proc/pvr exist)"
-  exit 1
-fi
-
-HWPERF_FW_FILTER_FILE="$DEBUG_DIR/apphint/HWPerfFWFilter"
-HWPERF_HOST_FILTER_FILE="$DEBUG_DIR/apphint/HWPerfHostFilter"
-
-preserve_state
-
-export PVRDebugLevel=0x00
-
+# check if any filter is enabled first so that we can terminate before any
+# filter is set
 if [ x"$HWPERF_FW_FILTER" != x ] || [ x"$HWPERF_HOST_FILTER" != x ]; then
   if [ x"$OS" = xANDROID ]; then
     USERID=$USER_ID
@@ -219,41 +244,74 @@ if [ x"$HWPERF_FW_FILTER" != x ] || [ x"$HWPERF_HOST_FILTER" != x ]; then
   # as regular user
   if [ "$USERID" != "0" ]; then
     echo "[Error] This script needs to be executed with root privileges"
-    restore_state
     exit 1
   fi
 
-  if [ x"$HWPERF_FW_FILTER" != x ]; then
-    if [ ! -f $HWPERF_FW_FILTER_FILE ]; then
-      echo "[Error] Could not set HW performance events filter"
-      restore_state
-      exit 1
-    fi
-
-    echo $HWPERF_FW_FILTER > $HWPERF_FW_FILTER_FILE 2>/dev/null
-    if [ $? != 0 ]; then
-      echo "[Error] Failed to set HW performance filter"
-      echo "        Check if the parameters passed to the script are valid"
-      restore_state
-      exit 1
-    fi
-  fi
-  if [ x"$HWPERF_HOST_FILTER" != x ]; then
-    if [ ! -f $HWPERF_HOST_FILTER_FILE ]; then
-      echo "[Error] Could not set host events filter"
-      restore_state
-      exit 1
-    fi
-
-    echo $HWPERF_HOST_FILTER > $HWPERF_HOST_FILTER_FILE 2>/dev/null
-    if [ $? != 0 ]; then
-      echo "[Error] Failed to set host events filter"
-      echo "        Check if the parameters passed to the script are valid"
-      restore_state
-      exit 1
-    fi
+  # if we have root privileges we can check for the debug files 
+  if [ -d "/sys/kernel/debug/pvr" ]; then
+    DEBUG_DIR="/sys/kernel/debug/pvr"
+  elif [ -d "/proc/pvr" ]; then
+    DEBUG_DIR="/proc/pvr"
+  else
+    echo "Error: No valid debug path (Neither /sys/kernel/debug/pvr or /proc/pvr exist)"
+    exit 1
   fi
 fi
+
+if [ x"$DEVICE" = xall ]; then
+  DEVICES=$(seq -w $MIN_DEVICE_ID $MAX_DEVICE_ID)
+else
+  DEVICES=$DEVICE
+fi
+
+# needs to be executed before "preserve_state"
+for ID in $DEVICES; do
+  eval "HWPERF_FW_FILTER_FILE_$ID=\"$DEBUG_DIR/gpu$ID/apphint/HWPerfFWFilter\""
+  eval "HWPERF_HOST_FILTER_FILE_$ID=\"$DEBUG_DIR/gpu$ID/apphint/HWPerfHostFilter\""
+done
+
+preserve_state
+
+export PVRDebugLevel=0x00
+
+for ID in $DEVICES; do
+  eval "_FW_FILTER_FILE=\$HWPERF_FW_FILTER_FILE_$ID"
+  eval "_HOST_FILTER_FILE=\$HWPERF_HOST_FILTER_FILE_$ID"
+
+  if [ x"$HWPERF_FW_FILTER" != x ] || [ x"$HWPERF_HOST_FILTER" != x ]; then
+    if [ x"$HWPERF_FW_FILTER" != x ]; then
+      if [ ! -f $_FW_FILTER_FILE ] && [ x"$DEVICE" != xall ]; then
+        echo "[Error] Could not set HW performance events filter"
+        restore_state
+        exit 1
+      fi
+
+      echo $HWPERF_FW_FILTER 2>/dev/null > $_FW_FILTER_FILE 2>/dev/null
+      if [ $? != 0 ] && [ x"$DEVICE" != xall ]; then
+        echo "[Error] Failed to set HW performance filter"
+        echo "        Check if the parameters passed to the script are valid"
+        restore_state
+        exit 1
+      fi
+    fi
+
+    if [ x"$HWPERF_HOST_FILTER" != x ]; then
+      if [ ! -f $_HOST_FILTER_FILE ] && [ x"$DEVICE" != xall ]; then
+        echo "[Error] Could not set host events filter"
+        restore_state
+        exit 1
+      fi
+
+      echo $HWPERF_HOST_FILTER 2>/dev/null > $_HOST_FILTER_FILE 2>/dev/null
+      if [ $? != 0 ] && [ x"$DEVICE" != xall ]; then
+        echo "[Error] Failed to set host events filter"
+        echo "        Check if the parameters passed to the script are valid"
+        restore_state
+        exit 1
+      fi
+    fi
+  fi
+done
 
 # ENVIRONMENT SETUP
 # - Create working directory
@@ -291,6 +349,10 @@ if [ "$HWPERF_RESET_STREAMS" = "true" ]; then
 echo "reset_on_open=\"yes\"" >> $CFG_FILE
 fi
 
+if [ x"$DEVICE" != xall ]; then
+echo "device=$DEVICE" >> $CFG_FILE
+fi
+
 echo "
 [hwperf_host_]
 enabled=yes
@@ -306,6 +368,10 @@ if [ "$HWPERF_RESET_STREAMS" = "true" ]; then
 echo "reset_on_open=\"yes\"" >> $CFG_FILE
 fi
 
+if [ x"$DEVICE" != xall ]; then
+echo "device=$DEVICE" >> $CFG_FILE
+fi
+
 echo "
 [hwperf_client_]
 enabled=yes
@@ -318,6 +384,10 @@ fi
 
 if [ "$HWPERF_RESET_STREAMS" = "true" ]; then
 echo "reset_on_open=\"yes\"" >> $CFG_FILE
+fi
+
+if [ x"$DEVICE" != xall ]; then
+echo "device=$DEVICE" >> $CFG_FILE
 fi
 
 # EXECUTION
diff --git a/rgx_um/vendor/bin/pvrlogdump b/rgx_um/vendor/bin/pvrlogdump
--- a/rgx_um/vendor/bin/pvrlogdump
+++ b/rgx_um/vendor/bin/pvrlogdump
@@ -1,3 +1,5 @@
+#!/bin/sh
+
 ################################################################################
 # @Copyright     Copyright (c) Imagination Technologies Ltd.
 #                All Rights Reserved
@@ -167,8 +169,8 @@ perform_check() {
 
     echo -n "Checking for firmware log groups .... "
     local FW_LOG_GROUPS_EN=false
-    if [ -f $PVR_DEBUGFS_PATH/apphint/0/EnableLogGroup ] && \
-       [ $(cat $PVR_DEBUGFS_PATH/apphint/0/EnableLogGroup) != "none" ]; then
+    if [ -f $PVR_DEBUGFS_PATH/gpu00/apphint/EnableLogGroup ] && \
+       [ $(cat $PVR_DEBUGFS_PATH/gpu00/apphint/EnableLogGroup) != "none" ]; then
         FW_LOG_GROUPS_EN=true
     else
         if [ -f $PVRINI_PATH ]; then
@@ -282,51 +284,66 @@ dump_fw_snapshot() {
         fi
     fi
 
-    local FW_TRACE=$PVR_DEBUGFS_PATH/firmware_trace
-    local DEBUG_DUMP=$PVR_DEBUGFS_PATH/debug_dump
+    # handle multidevice case where there can be per device (gpuXX)
+    # subdirectories
+    local DEVICES="$(ls -d $PVR_DEBUGFS_PATH/gpu* 2>/dev/null)"
+    if [ -z "$DEVICES" ]; then
+        local DEVICES="$PVR_DEBUGFS_PATH"
+    fi
 
-    for IDX in 1 2; do
-        # if there is a firmware log file dump it for our convenience
-        if [ -f $FW_TRACE ]; then
-            echo ""
-            echo "==== firmware_trace ($IDX) ===="
-            echo ""
-            cat $FW_TRACE
+    for PVR_DEBUGFS_DEVICE_PATH in $DEVICES; do
+        local DEVICE_ID=$(basename $PVR_DEBUGFS_DEVICE_PATH)
+        local FW_TRACE=$(readlink -f $PVR_DEBUGFS_DEVICE_PATH)/firmware_trace
+        local DEBUG_DUMP=$(readlink -f $PVR_DEBUGFS_DEVICE_PATH)/debug_dump
+
+        # in case the script is run on an older DDK with no device subdirs
+        if [ "${DEVICE_ID}" = "pvr" ]; then
+            local DEVICE_ID="gpu00"
         fi
 
-        # if there is debug_dump file then dump it but if for some reason it's
-        # absent use dmesg to obtain it
-        if [ -f $DEBUG_DUMP ]; then
-            echo ""
-            echo "==== debug_dump ($IDX) ===="
-            echo ""
-            cat $DEBUG_DUMP
-        else
-            echo ""
-            echo "==== dmesg ($IDX) ===="
-            echo ""
-            if [ -c /dev/kmsg ]; then
-                echo "" >/dev/kmsg
-                echo "==== debug_dump ($IDX) ====" >/dev/kmsg
-                echo "" >/dev/kmsg
+        for IDX in 1 2; do
+            # if there is a firmware log file dump it for our convenience
+            if [ -f $FW_TRACE ]; then
+                echo ""
+                echo "==== firmware_trace ($DEVICE_ID, $IDX) ===="
+                echo ""
+                cat $FW_TRACE
             fi
-            if command -v pvrdebug >/dev/null 2>&1; then
-                if ! pvrdebug -dd >/dev/null 2>&1; then
-                    if [ -c /dev/kmsg ]; then
-                        echo "pvrdebug failed" >/dev/kmsg
+
+            # if there is debug_dump file then dump it but if for some reason
+            # it's absent use dmesg to obtain it
+            if [ -f $DEBUG_DUMP ]; then
+                echo ""
+                echo "==== debug_dump ($DEVICE_ID, $IDX) ===="
+                echo ""
+                cat $DEBUG_DUMP
+            else
+                echo ""
+                echo "==== dmesg ($DEVICE_ID, $IDX) ===="
+                echo ""
+                if [ -c /dev/kmsg ]; then
+                    echo "" >/dev/kmsg
+                    echo "==== debug_dump ($DEVICE_ID, $IDX) ====" >/dev/kmsg
+                    echo "" >/dev/kmsg
+                fi
+                if command -v pvrdebug >/dev/null 2>&1; then
+                    if ! pvrdebug -dd >/dev/null 2>&1; then
+                        if [ -c /dev/kmsg ]; then
+                            echo "pvrdebug failed" >/dev/kmsg
+                        fi
                     fi
                 fi
+                dmesg
             fi
-            dmesg
-        fi
 
-        # skip sleep on last iteration
-        if [ $IDX -ne 2 ]; then
-            # Android, ChromeOS and most Linux distributions accept time as
-            # a floating point number so wait for 10ms
-            # but e.g. busybox supports only integers so wait for 1s
-            if ! sleep 0.01 >/dev/null 2>&1; then sleep 1; fi
-        fi
+            # skip sleep on last iteration
+            if [ $IDX -ne 2 ]; then
+                # Android, ChromeOS and most Linux distributions accept time as
+                # a floating point number so wait for 10ms
+                # but e.g. busybox supports only integers so wait for 1s
+                if ! sleep 0.01 >/dev/null 2>&1; then sleep 1; fi
+            fi
+        done
     done
 }
 
